version: 0.2

env:
  variables:
    STRIPE_SECRET_KEY: stripe_key_stub

phases:
  install:
    commands:
      - # gem install bundler
      - bundle install
  pre_build:
    commands:
      - bundle exec rspec
      - rm logs/test.log
      - rm -rf tmp/cache
artifacts:
  files: '**/*'
  name: ncma-api_$(date +%Y-%m-%dT%H:%M:%S_`echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7`)
