version: 0.2

env:
  variables:
    STRIPE_SECRET_KEY: stripe_key_stub

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo ruby -v
  pre_build:
    commands:
      - echo -- Build started on `date`
      - bundle install --deployment
      - rspec
  build:
    commands:
      - bundle package
  pre_build:
    commands:
      - echo -- Build completed at `date`

artifacts:
  name: ncma-api-$(date +%Y-%m-%dT%H:%M:%S_`cat .git/refs/heads/master | cut -c1-7`)
