version: 0.2

env:
  variables:
    STRIPE_SECRET_KEY: stripe_key_stub

phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - gem install bundler
      - bundle install --deployment
  pre_build:
    commands:
      - bundle exec rspec
  build:
    commands:
      - bundle install --without development test
      - bundle package
artifacts:
  name: ncma-api-$(date +%Y-%m-%dT%H:%M:%S_`echo CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7`)