version: 0.2

env:
  variables:
    STRIPE_SECRET_KEY: stripe_key_stub

phases:
  install:
    runtime-versions:
      ruby: 2.6
  pre_build:
    commands:
      - bundle install --deployment
      - rspec
  build:
    commands:
      - bundle package